"""Sample content, so `tabless demo` shows you the thing instead of describing it.

The samples are written to a temporary directory, archived, and then the
temporary directory is deleted. That sequence is the point: what you end up
reading in the library is tabless's own copy, and the originals being gone
changes nothing. That is the difference between this and a list of bookmarks.

The batch is deliberately mixed -- two projects, four types, and all three kinds
of entry -- so the reader has something to actually group.
"""

from __future__ import annotations

import shutil
import tempfile
from pathlib import Path

from . import core

_STYLE = """
 :root{--bg:#0e1116;--card:#161b24;--line:#242b38;--tx:#dde3ec;--dim:#8b95a6;--ac:#2dd4bf}
 *{box-sizing:border-box}
 body{margin:0;padding:44px 30px;background:var(--bg);color:var(--tx);
   font:15px/1.75 system-ui,"Segoe UI","PingFang SC",sans-serif}
 main{max-width:720px;margin:0 auto}
 h1{font-size:26px;margin:0 0 6px;letter-spacing:-.01em}
 .lede{color:var(--dim);margin:0 0 30px;font-size:14px}
 h2{font-size:16px;margin:32px 0 10px;color:var(--ac);font-weight:600}
 p{margin:0 0 14px}
 .card{background:var(--card);border:1px solid var(--line);border-radius:12px;
   padding:20px 24px;margin:18px 0}
 code{background:#0b0d12;border:1px solid var(--line);border-radius:5px;
   padding:1px 6px;font-size:13px;color:var(--ac)}
 table{width:100%;border-collapse:collapse;margin:14px 0;font-size:14px}
 th,td{text-align:left;padding:8px 10px;border-bottom:1px solid var(--line)}
 th{color:var(--dim);font-weight:500;font-size:12px;text-transform:uppercase;
   letter-spacing:.06em}
 a{color:var(--ac)}
 .foot{margin-top:40px;padding-top:16px;border-top:1px solid var(--line);
   color:#5d6675;font-size:12px}
"""


def _page(title: str, lede: str, body: str) -> str:
    return (f"<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">"
            f"<title>{title}</title><style>{_STYLE}</style></head><body><main>"
            f"<h1>{title}</h1><p class=\"lede\">{lede}</p>{body}"
            f"<p class=\"foot\">Sample content generated by <code>tabless demo</code>."
            f"</p></main></body></html>")


_CHART_SVG = """<svg xmlns="http://www.w3.org/2000/svg"
     viewBox="0 0 320 120" width="320" height="120">
  <rect width="320" height="120" fill="#0b0d12" rx="8"/>
  <g fill="#2dd4bf">
    <rect x="24" y="70" width="34" height="34" rx="3"/>
    <rect x="72" y="46" width="34" height="58" rx="3"/>
    <rect x="120" y="28" width="34" height="76" rx="3"/>
    <rect x="168" y="58" width="34" height="46" rx="3"/>
    <rect x="216" y="18" width="34" height="86" rx="3"/>
    <rect x="264" y="40" width="34" height="64" rx="3"/>
  </g>
  <line x1="16" y1="104" x2="304" y2="104" stroke="#242b38" stroke-width="1"/>
</svg>
"""

_SAMPLES = [
    {
        "name": "weekly-review.html",
        "project": "acme",
        "type": "report",
        "html": _page(
            "Checkout latency, week 31",
            "What moved, what didn't, and the one thing worth doing next week.",
            """
<div class="card"><p>Median checkout latency fell from <code>840ms</code> to
<code>410ms</code> after the session lookup was moved off the critical path.
The tail did not move, and the tail is where the complaints come from.</p></div>
<h2>Where the time goes now</h2>
<table>
  <tr><th>Stage</th><th>p50</th><th>p99</th></tr>
  <tr><td>Session lookup</td><td>12ms</td><td>38ms</td></tr>
  <tr><td>Inventory check</td><td>96ms</td><td>1.9s</td></tr>
  <tr><td>Payment authorisation</td><td>210ms</td><td>2.4s</td></tr>
</table>
<h2>Next</h2>
<p>Both tail contributors are third-party calls with no timeout budget. Giving
them one is a smaller change than making them faster, and it is the change that
users would actually feel.</p>
"""),
    },
    {
        "name": "retention-spec.html",
        "project": "acme",
        "type": "doc",
        "html": _page(
            "Data retention rules",
            "The reference you come back to, not a write-up you read once.",
            """
<h2>Retention windows</h2>
<table>
  <tr><th>Class</th><th>Kept for</th><th>Then</th></tr>
  <tr><td>Request logs</td><td>30 days</td><td>Deleted</td></tr>
  <tr><td>Audit events</td><td>7 years</td><td>Cold storage</td></tr>
  <tr><td>Derived analytics</td><td>13 months</td><td>Aggregated, then deleted</td></tr>
</table>
<h2>Why this is a doc and not a report</h2>
<p>The test is what the page is <em>for the reader</em>, not what it is about.
You will come back to this table; you will not re-read last week's latency
numbers. That is the whole distinction.</p>
"""),
    },
    {
        "name": "orbital-status.html",
        "project": "orbital",
        "type": "report",
        "html": _page(
            "Ground station handover",
            "A second project, so the reader has more than one tab to show.",
            """
<div class="card"><p>Handover now completes inside the 40-second window in
eleven of twelve passes. The twelfth is the low-elevation pass over the
southern station, which has never once succeeded and probably never will
without a second antenna.</p></div>
<h2>Open question</h2>
<p>Whether to keep scheduling that pass at all. It costs a retry budget and
returns nothing.</p>
"""),
    },
]

_SITE_INDEX = _page(
    "Prompt variants, run 4",
    "An experiment board: several linked pages plus an image, so it is archived as a site.",
    """
<div class="card"><p>Six variants, 240 samples each. Variant D wins on
faithfulness without losing brevity; everything else is noise at this sample
size.</p></div>
<img src="assets/chart.svg" alt="Scores by variant" width="320" height="120">
<h2>Cases</h2>
<p><a href="case-01.html">Case 01 — the disagreement</a></p>
<h2>Why this one is a site</h2>
<p>It references a sibling page and an image. tabless follows the dependency
closure, copies exactly those files with their relative structure intact, and
files the whole thing as one entry rather than three.</p>
""")

_SITE_CASE = _page(
    "Case 01 — the disagreement",
    "The one sample where the graders split.",
    """
<div class="card"><p>Two graders called variant B faithful, two called it a
fabrication. Re-reading it, both are right: the claim is true and the citation
attached to it is not.</p></div>
<p><a href="index.html">← Back to the board</a></p>
""")


def install() -> list[dict]:
    """Write the samples, archive them, delete the originals, return the entries."""
    tmp = Path(tempfile.mkdtemp(prefix="tabless-demo-"))
    try:
        entries = []
        for sample in _SAMPLES:
            path = tmp / sample["name"]
            path.write_text(sample["html"], encoding="utf-8")
            entries.append(core.add_document(
                path, project=sample["project"], doctype=sample["type"],
                source="demo",
            ))

        board = tmp / "board"
        (board / "assets").mkdir(parents=True, exist_ok=True)
        (board / "assets" / "chart.svg").write_text(_CHART_SVG, encoding="utf-8")
        (board / "case-01.html").write_text(_SITE_CASE, encoding="utf-8")
        (board / "index.html").write_text(_SITE_INDEX, encoding="utf-8")
        entries.append(core.add_document(
            board / "index.html", project="acme", doctype="eval", source="demo",
        ))

        entries.append(core.add_live(
            target="http://localhost:5173/",
            project="orbital",
            title="Pass planner (live prototype)",
            hint="Run `npm run dev` in web/ first — tabless will not start it for you.",
            source="demo",
        ))
        return entries
    finally:
        # The originals go away and the library is unaffected. That is the demo.
        shutil.rmtree(tmp, ignore_errors=True)
